#!/bin/sh
#
# This file is part of the SavaPage project <https://www.savapage.org>.
# Copyright (c) 2011-2017 Datraverse B.V.
# Author: Rijk Ravestein.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# For more information, please contact Datraverse B.V. at this
# address: info@datraverse.com
#

#-------------------------
NFC_SERVICE=savapage-nfc

#-------------------------
install_arch=armv6l
system_arch=`uname -m 2>/dev/null`
if [ "${system_arch}" != "${install_arch}" ]; then
    echo "This release is designed for ${install_arch} systems."
	echo "Install aborted!"
	exit 1
fi


#
# Checks if packages are present.
#
check_packages() {

	echo "Checking installed packages ..."
	
	ldderror=
	
    packages="libccid
		 	libacsccid1
            pcscd"

    for package in ${packages}; do
    	
		dpkg -s ${package} >/dev/null 2>&1
		pkg_present=$?
		
		if [ "${pkg_present}" = 0 ]; then
			echo "${package}: installed"
		else
			echo "${package}: NOT installed" >&2
			ldderror=y 
		fi
				
    done
    
	if [ "${ldderror}" = "y" ]; then    	    	
		echo "Unable to install. One or more packages need to be installed." >&2
		echo "Install aborted!" >&2
    	exit 1
	fi
}

check_packages

#-------------------------
sudo cp /usr/local/bin/savapage/${NFC_SERVICE} /etc/init.d
sudo update-rc.d ${NFC_SERVICE} defaults
sudo service ${NFC_SERVICE} start

#-------------------------
echo "Connect the NFC reader and speakers."   	
echo "Swipe a card to test. You should hear a sound."   	
