#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          savapage-nfc
# Required-Start:    $remote_fs $syslog pcscd
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SavaPage Network Card Reader
# Description:       Network Card Reader for Mifare RFID Cards
### END INIT INFO
 
# The next 3 lines specify where the savapage-nfc-reader executable 
# is installed and how the service is called.
DIR=/usr/local/bin/savapage
DAEMON=$DIR/savapage-nfc-reader
DAEMON_NAME=savapage-nfc
 
# This next line determines what user the script runs as.
# (root user is not recommended)
DAEMON_USER=pi
 
# The process ID of the service when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid
 
. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting $DAEMON_NAME service"
    start-stop-daemon --start --quiet --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --startas $DAEMON --chdir $DIR
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping $DAEMON_NAME service"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 10
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0
