name: Build print server

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: openjdk-8-jdk maven g++ make pkg-config zip libcups2-dev libpam0g-dev cups-ppdc
        version: 1.0

    - name: Build
      run: make all

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: nirvati-print-install.bin
        # A file, directory or wildcard pattern that describes what to upload
        path: target/savapage-setup-*-linux-x64.bin
